#https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-andreas-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-andreas-demo
  template:
    metadata:
      labels:
        app: azure-andreas-demo
    spec:
      containers:
      - name: azure-andreas-demo
        image: andreasdemo.azurecr.io/images/andreasdemo
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azure-andreas-demo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "4"
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "svc"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-andreas-demo
